import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  // Brand/Seed Colors (the only colors you need to define)
  static const Color brandPrimary = Color(0xFF6750A4);

  // Optional: Additional semantic colors not generated by M3
  static const Color success = Color(0xFF4CAF50);
  static const Color warning = Color(0xFFFFC107);
  static const Color info = Color(0xFF2196F3);
}
